### PR TITLE
upgrade to play 2.6.x

### PR DESCRIPTION
**Pull request by Enalmada**
A 2.6.x build on scala 2.12 would be awesome!  Unfortunately I don't quite know enough to make it worth merging as is....but I wanted to at least try.   Hopefully it helps!

### CODE REVIEW

**Comment by sief** [comment]
Thanks @Enalmada , looks great,  I'll take a closer look at it over the weekend. 
BTW: I wanted the next release to be 2.1.0. Could you change the version back to 2.1.0-SNAPSHOT?

**Comment by Enalmada** [comment]
Notes: 

-- The module and guice sample seems to work...but...
-- I couldn't quite figure out how to get the other sample compiling with the non injected controller helpers
-- I tried to pass through ExecutionContext as that seems to be recommended in 2.6 (global is deprecated), but in retrospect it might be simpler to just continue to use the global implicit for now since it looks like play-guard is non-blocking...up to you
-- I must admit I don't really get what play 2.6 did with bodyParsers...I hacked something in to make it (appear to) work but I suspect everything i did with bodyParser is wrong and there is a better way to make play happy.
-- Although off topic, I have added some code to the clientIp function to look for proxy header first (since if it exists, the remoteAddress will probably always be the actual proxy ip which is probably never a desirable default in that case):
```
      // Consider X-Forward-For as most accurate if it exists
      // Since it is easy to forge an X-Forwarded-For, only consider the last ip added by our proxy as the most accurate
      // https://en.wikipedia.org/wiki/X-Forwarded-For
      request.headers.get("X-Forward-For").map(_.split(",").last.trim).getOrElse {
        request.remoteAddress
      }
```

Oh, and i just changed the scala version to 2.12.  I assume people using this new version will also be on 2.12, but if you think people will want to use 2.11 too we could put cross compile.

**Comment by sief** [comment]
regarding the off-topic: you're right, only the last IP in the list is reliable, but this might be a proxy. Here is an interesting discussion on SO https://stackoverflow.com/questions/18264304/get-clients-real-ip-address-on-heroku . 
So I'd like to keep it as it was for now. If configured, it just reads the entire header value, which I think is OK for the purpose. I've put a pluggable clientIp mechanism on top of my backlog ;)

**Comment by sief** [comment]
My other projects still have 2.11 dependencies, so I definitely need to cross compile 2.11/2.12. Can't hurt anyway.

**Comment by sief** [comment]
Here is a patch that fixes the bodyParser handling and the compile time DI sample. Haven't looked at the guice sample yet. 

[compile_time_DI__bodyParser_handling.txt](https://github.com/sief/play-guard/files/1150470/compile_time_DI__bodyParser_handling.txt)

**Comment by Enalmada** [comment]
I believe that if an x-forwarded-for header exists, the remoteAddress value will never be accurate so checking for it first seems like required behavior.  I strongly suspect most if not all production configurations would use some sort of proxy (heroku, beanstalk, or manual loadbalancer) so checking for it first will prevent users from rolling something out that will throttle everyone without them realizing it.

My takeaway from that stackoverflow (and wikipedia and aws loadbalancer docs), is that using last ip is generally the best thing to do.  I don't think waiting for a pluggable clienttIp is necessary.  The proposed solution would be most functional and secure for the average user out of the box and someone who wants to use the whole x-forward header (at their own risk of a client being able to disable brute force protection from a single actual ip by passing faked headers),  they can just define their header with "playguard.clientipheader".

**Comment by sief** [comment]
ok, you're right, last IP is the best option

**Comment by Enalmada** [comment]
Ok, I have added your compile time changes...everything builds and tests pass now thanks!
(Note that I have forced pushed the update so all changes are all cleanly in one commit)

**Comment by sief** [comment]
just released 2.1.0: https://mvnrepository.com/artifact/com.digitaltangible/play-guard_2.12/2.1.0.  
@Enalmada thanks for your contribution.

**Pull request merged**
